run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
linters-settings:
  goimports:
    local-prefixes: github.com/lucasew/go-getlistener
